require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ConcretePackageStatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ConcretePackageState. As you add validations to ConcretePackageState, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConcretePackageStatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all concrete_package_states as @concrete_package_states" do
      concrete_package_state = ConcretePackageState.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:concrete_package_states)).to eq([concrete_package_state])
    end
  end

  describe "GET #show" do
    it "assigns the requested concrete_package_state as @concrete_package_state" do
      concrete_package_state = ConcretePackageState.create! valid_attributes
      get :show, {:id => concrete_package_state.to_param}, valid_session
      expect(assigns(:concrete_package_state)).to eq(concrete_package_state)
    end
  end

  describe "GET #new" do
    it "assigns a new concrete_package_state as @concrete_package_state" do
      get :new, {}, valid_session
      expect(assigns(:concrete_package_state)).to be_a_new(ConcretePackageState)
    end
  end

  describe "GET #edit" do
    it "assigns the requested concrete_package_state as @concrete_package_state" do
      concrete_package_state = ConcretePackageState.create! valid_attributes
      get :edit, {:id => concrete_package_state.to_param}, valid_session
      expect(assigns(:concrete_package_state)).to eq(concrete_package_state)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ConcretePackageState" do
        expect {
          post :create, {:concrete_package_state => valid_attributes}, valid_session
        }.to change(ConcretePackageState, :count).by(1)
      end

      it "assigns a newly created concrete_package_state as @concrete_package_state" do
        post :create, {:concrete_package_state => valid_attributes}, valid_session
        expect(assigns(:concrete_package_state)).to be_a(ConcretePackageState)
        expect(assigns(:concrete_package_state)).to be_persisted
      end

      it "redirects to the created concrete_package_state" do
        post :create, {:concrete_package_state => valid_attributes}, valid_session
        expect(response).to redirect_to(ConcretePackageState.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved concrete_package_state as @concrete_package_state" do
        post :create, {:concrete_package_state => invalid_attributes}, valid_session
        expect(assigns(:concrete_package_state)).to be_a_new(ConcretePackageState)
      end

      it "re-renders the 'new' template" do
        post :create, {:concrete_package_state => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested concrete_package_state" do
        concrete_package_state = ConcretePackageState.create! valid_attributes
        put :update, {:id => concrete_package_state.to_param, :concrete_package_state => new_attributes}, valid_session
        concrete_package_state.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested concrete_package_state as @concrete_package_state" do
        concrete_package_state = ConcretePackageState.create! valid_attributes
        put :update, {:id => concrete_package_state.to_param, :concrete_package_state => valid_attributes}, valid_session
        expect(assigns(:concrete_package_state)).to eq(concrete_package_state)
      end

      it "redirects to the concrete_package_state" do
        concrete_package_state = ConcretePackageState.create! valid_attributes
        put :update, {:id => concrete_package_state.to_param, :concrete_package_state => valid_attributes}, valid_session
        expect(response).to redirect_to(concrete_package_state)
      end
    end

    context "with invalid params" do
      it "assigns the concrete_package_state as @concrete_package_state" do
        concrete_package_state = ConcretePackageState.create! valid_attributes
        put :update, {:id => concrete_package_state.to_param, :concrete_package_state => invalid_attributes}, valid_session
        expect(assigns(:concrete_package_state)).to eq(concrete_package_state)
      end

      it "re-renders the 'edit' template" do
        concrete_package_state = ConcretePackageState.create! valid_attributes
        put :update, {:id => concrete_package_state.to_param, :concrete_package_state => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested concrete_package_state" do
      concrete_package_state = ConcretePackageState.create! valid_attributes
      expect {
        delete :destroy, {:id => concrete_package_state.to_param}, valid_session
      }.to change(ConcretePackageState, :count).by(-1)
    end

    it "redirects to the concrete_package_states list" do
      concrete_package_state = ConcretePackageState.create! valid_attributes
      delete :destroy, {:id => concrete_package_state.to_param}, valid_session
      expect(response).to redirect_to(concrete_package_states_url)
    end
  end

end
